name: Run Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Define the Rust versions to test against
        rust-version: [ "1.83.0", "stable", "beta" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang curl pkg-config libssl-dev make
          make install-deps

      - name: Run Tests and Generate Coverage Report
        run: make coverage # Generates a coverage report

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        continue-on-error: false
